### PR TITLE
Some extensions

### PR DESCRIPTION
**Pull request by soef**
Object View:
- Sort option added to object view
- Icon size in object view icon column reduced from 20 to 16 px
- Distance between icon and name column extended
- admin.js._delObject function overworked
- bugfix: when deleting an object with childs, now all entries will disappear
- some tree.visit loops replace by tree.getNodeByKey
- expanded folders will now stay expanded after a tree view refresh
- selectID.js.findTree overworked
- selectID.js.treeInsert overworked
- bugfix: selectID.js.filterid extended to filter out not expert entries (for entries inserted by object change)

### CODE REVIEW

**Comment by Apollon77** [comment]
Wow, many cool things!
testing fails currently because version of package.json is not increased ...

**Comment by GermanBluefox** [comment]
Super. I waited a long time to get someone to fix this error with the nodes delete. Thank you.

**Comment by GermanBluefox** [comment]
Hi Soef,
there is some problem.
image

I have *system.adapter.cloud.0* and *system.adapter.cloud.1* and there is no objects for that and all states are together in one.

**Comment by soef** [comment]
Oh, I'll take care of it tomorrow at the latest.

**Pull request merged**
