### PR TITLE
add attribute alsoDependsOn to selectSendTo and autocompleteSendTo

### PR DESCRIPTION
**Pull request by Jey-Cee**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
@Jey-Cee Thank you.
Could you please remove the *.map changes from this PR?
And can you restore the formatting of SCHEMA.md?

**Comment by Jey-Cee** [comment]
I've removed the files from the PR, but i am not sure what will happen when you merge this PR.

**Comment by Jey-Cee** [comment]
It is better you make a commit by yourself, i am not sure why all this changes was there and do not know how to remove it in fast way.

**Comment by Apollon77** [comment]
Hm ... but closing it now makes it invisible for anyone

**Pull request closed without merging**
