### PR TITLE
Better integration for ioBroker.info

### PR DESCRIPTION
**Pull request by ldittmar81**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you!
I am not sure about "async" in all modern browsers.... @AlCalzone do you know?

**Comment by ldittmar81** [comment]
You can see it here:

https://caniuse.com/#feat=async-functions

**Comment by AlCalzone** [comment]
So basically all but legacy IE

**Comment by ldittmar81** [comment]
@AlCalzone BF has said browser and IE is definitely not a browser :rofl:

**Comment by ldittmar81** [comment]
Should I display an info if the Info Adapter is not installed, with the option to install the current version or update to the current stable version, if it is smaller than 1.3.7?

**Pull request merged**
