### PR TITLE
Add message check for active instance

### LINKED ISSUE #503: ENhance new conditions by "enabled" for popup
https://github.com/iobroker-community-adapters/ioBroker.info/issues/67

### PR DESCRIPTION
**Pull request by ldittmar81**
This will fix #503

### CODE REVIEW

**Comment by Apollon77** [comment]
@WLAN-Kabel @GermanBluefox Please check and merge for react version/both

**Comment by WLAN-Kabel** [comment]
The info part is not yet implemented in the React version.

**Comment by ldittmar81** [comment]
@Apollon77 @WLAN-Kabel We should release these changes so that the info messages are displayed correctly.

**Comment by GermanBluefox** [comment]
I am resolutely against to write the UUIDs and not the hashes in messages!

**Comment by Apollon77** [comment]
@ldittmar81 can you move the "uuid hashing" into this Admin PR please and adjust Info adapter  (because then no additional hashing is needed) and we make sure the the UUID is not used outside of the adapter javascript server side code

**Comment by ldittmar81** [comment]
No UUID is used here. The Info Adapter creates a hash from UUID + x at startup and that is exactly what is used here. Nowhere is the UUID compared, only this hash.

The hash code is generated here:
https://github.com/iobroker-community-adapters/ioBroker.info/blob/ed35e2e6094941eae11c5e2d9c681ce6136e1fc2/main.js#L101

Here I get the hash code from the Info Adapter:
https://github.com/ioBroker/ioBroker.admin/pull/561/files#diff-6377329007b146d647a822e859d7250eR221

**Comment by ldittmar81** [comment]
> I am resolutely against to write the UUIDs and not the hashes in messages!

You must create a hash of "iobroker-uuid" + UUID for the messages...

**Pull request merged**
