### PR TITLE
create jsonConfig guide based on schema.md

### PR DESCRIPTION
**Pull request by oweitman**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Looks cool. Thank you!
Have you created settings automatically or manually?

**Comment by mcm1957** [comment]
Formatting and explanation looks good. 

**BUT why do we need TWO files here?**
Why not adapting the existing SCHEMA.md and adapt formatting and instructs there?

Two files with same information are getting inkonstitent for sure if they are not created by an automatism. Of course a README.md can be created and SCHEMA.md be removed. But in this case do not forget to leave a minimum SCHEMA.md pointing to to new documentation as it will last some time to change all referneces pointing at SCHAME,md

**Comment by oweitman** [comment]
because this is just a proposal and I don't know if it will be accepted. Also, I didn't want to delete bluefox schema.md.
if someone thinks the document is good enough to replace schema.md, then I'm fine with that.

**Comment by mcm1957** [comment]
Ok, the proposal would not replace anything until ist merged :-)
I only want to point out that we should not have 2 Places with identical documentation which are not synched automatically. And at the first look I did not recognize that you created a new file - was focused on content.

Think BF will take care of this.

**Comment by oweitman** [comment]
> Looks cool. Thank you! Have you created settings automatically or manually?

which settings?
the md settings?
i didnt install anything in the repo.
i only installed the vs code extension markdownlinter
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Comment by mcm1957** [comment]
I could not finde the attributes for tabs, i.e. tabsStyle.
The attributes are mentioned here:

```
tabs - Tabs with items

items - Object with panels {"tab1": {}, "tab2": {}...}

iconPosition - bottom, end, start or top. Only for panels that has icon attribute. Default: start
tabsStyle - CSS Styles in React format (marginLeft and not margin-left) for the Mui-Tabs component
panel - Tab with items

icon - tab can have icon (base64 like data:image/svg+xml;base64,...) or jpg/png images (ends with .png)

label - Label of tab
items - Object {"attr1": {}, "attr2": {}}...
collapsable - only possible as not part of tabs[jsonConfig.json](https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/..%2F..%2F..%2F..%2F..%2FioBroker.ring%2Fadmin%2FjsonConfig.json)
color - color of collapsable header primary or secondary or nothing
innerStyle - CSS Styles for inner div in React format (marginLeft and not margin-left) for the Panel component. Not used for collapsable panels.

```

Please verify - maybe I did not search the right way.

**Comment by oweitman** [comment]
yes, I missed the 2 elements Tabs and Panel, I added these in the last commit

the minimum version is already mentioned. in general in section ## What you'll need
and if different in the element list and element details (i added a missing one)

Additionally, I have sorted the element index alphabetically

**Comment by mcm1957** [comment]
> the minimum version is already mentioned. in general in section ## What you'll need and if different in the element list and element details (i added a missing one)
> 
> Additionally, I have sorted the element index alphabetically

Thanks for adding and for sorting the indis. Was a good idea.

I still think, that noting the exact admin version required qould be a good idea. The notes from scema.md are incomplete. I do not think that i.e. devicemanager is working with admin 6.0.0 - but I did not test it. Where this information is notes - at the index tanle or at the heading area of every element is secondary. Adding to index would have the benefit t detect missing info easier but technical it should be located near the descripton of the component.

 Anyway this is not 100% related to the PR so its ok for me to wait until PR is merged and to open a issue afterwards

**Comment by oweitman** [comment]
I only have the informations that are mentioned in the schema.md

**Comment by mcm1957** [comment]
Bitte noch sendto in sendTo ändern. Das war/ist auch in Schema.md falsch
https://github.com/ioBroker/ioBroker.admin/pull/2792

**Comment by oweitman** [comment]
erledigt

**Comment by oweitman** [comment]
thank you for merge

**Pull request merged**
