### PR TITLE
button color in non-expert mode will not change according to ack/q anymore

### LINKED ISSUE #1832: Color of states with role 'button'
A state got a definition like:
```
"_id": "update",
  "type": "state",
  "common": {
    "role": "button",
    "name": "Manually trigger an update",
    "type": "boolean",
    "read": false,
    "write": true,
    "def": false
  },
```

The role `button` is easy to use for trigger something manually, but after first use the button gets a deep red color which might lead misunderstandings because this means `true` w/o `ack`. A button is only `true` when it is pushed, else it is `false`.

Please consider to not coloring the button or change its behavior to get a light red color after use.

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1832

### CODE REVIEW

**Comment by rovo89** [comment]
Not sure if I misunderstood this intention of this PR, but buttons still turn (and stay) red after pressing them, even with 6.6.1. :(

**Comment by foxriver76** [comment]
just tested with 6.6.1 and it stays black in my case, try to use a private tab to exclude caching issues, else I need some information how to reproduce ;-)

**Comment by rovo89** [comment]
I think I found the reason. Had role="button.stop". As soon as I change it to "button" the color changes to black.

**Comment by rovo89** [comment]
There are various ways to fix this, I proposed one in #1994. PTAL.

**Pull request merged**
