### PR TITLE
Translations update from ioBroker Translation System

### PR DESCRIPTION
**Pull request by ioBrokerTranslator**
Translations update from [ioBroker Translation System](https://weblate.iobroker.net) for [ioBroker Adapters/admin](https://weblate.iobroker.net/projects/adapters/admin/).

It also includes following components:

* [ioBroker Adapters/admin-dm-gui-components](https://weblate.iobroker.net/projects/adapters/admin-dm-gui-components/)

* [ioBroker Adapters/admin-web](https://weblate.iobroker.net/projects/adapters/admin-web/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by foxriver76 — CHANGES_REQUESTED** [review]
makes no sense from my pov

**Comment by mcm1957** [comment]
Please recheck.
This PR should be a NOP PR (no change fuinally) in the meantime. Glossary has been adapted for future.

**Review by Apollon77 — APPROVED** [review]

**Comment by Apollon77** [comment]
@foxriver76 how do we now best merge this so that weblate is ok with it? So no squash

**Comment by mcm1957** [comment]
Please check the files tab
There is NO change at all finally.
You shoukd be able to merge without any resulting change.
And weblate should fell ok if you simply close it too

**Comment by foxriver76** [comment]
What is different from normal weblate PRs? They are normally also squashed afaik

**Comment by Apollon77** [comment]
No normally it is merged by maintaining all commits ... we can also squash. but then I need to update weblate manually ... in fact weblate has an own fork inside and when you squash the commit history is different and he can not rebase that locally

**Comment by foxriver76** [comment]
Hm eh this one is also squashed etc as these repo settings exist for longer 

https://github.com/ioBroker/ioBroker.admin/pull/2324
See commit hash from weblate vs commit hash on master

**Comment by Apollon77** [comment]
squashed now ... we will see what weblate says :-)

**Comment by mcm1957** [comment]
Weblate serms to be happy.
No errors after manual update and push

**Pull request merged**
