### PR TITLE
Translations update from ioBroker Translation System

### PR DESCRIPTION
**Pull request by ioBrokerTranslator**
Translations update from [ioBroker Translation System](https://weblate.iobroker.net) for [ioBroker Adapters/admin](https://weblate.iobroker.net/projects/adapters/admin/).

It also includes following components:

* [ioBroker Adapters/admin-dm-gui-components](https://weblate.iobroker.net/projects/adapters/admin-dm-gui-components/)

* [ioBroker Adapters/admin-web](https://weblate.iobroker.net/projects/adapters/admin-web/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by mcm1957** [comment]
@Apollon77 

Not sure why this PR has been created. I definitly did NOT change anything at weblate within the last hours. Last action was adding solaredge - three days ago. So I have no clue why weblate lists those old commits again ...

Maybe this is caused by updates done externally (= new text added due to license infos). Those additions change the complete german file due to diffenrences in whitespaces if I'm corre ct reading that commit.

**Comment by foxriver76** [comment]
Probably really a problem with the squash merges..

**Comment by foxriver76** [comment]
would this maybe help us @Apollon77 https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits

I have never looked into weblate tbh

**Comment by mcm1957** [comment]
Looks like that addon will sqash outgoing commits (commits issued from weblate). As this will delete the change log inside the PR I'm not sure wether this will be a desired feature.

**Comment by foxriver76** [comment]
hm expected that.. then we would need to activate normal merge commits at least for weblate PRs

**Comment by mcm1957** [comment]
I'm still not sure wethe rthe squash merge is the main problem.

Currently admin is locke due to merge conflict.
I'n not sure whether the first weblate PR has been merger BEFORE the changes done by license translations. 

Maybe the problem is only caused by the fact that admin changes whitespaces in an incompatible way during translation. Normal nopm run translate does not seem to do this. So mayby the admin tool used fpor translations could be adjusted to matching indention and this would fix it too.

**Comment by foxriver76** [comment]
okay fyi I also merged a noop commit previously that day

**Review by foxriver76 — APPROVED** [review]

**Pull request merged**
