### PR TITLE
Add Chinese support

### PR DESCRIPTION
**Pull request by SchumyHao**
Hi ioBroker

I'm Schumy come from China.
I'm very excited that I found ioBroker today because there are lots of outstanding adapter in ioBroker.

We've done a lot of work promoting Homeassistant in China before. There is a BBS maintained by us which about [Homeassistant](https://bbs.hassbian.com/forum.php)
I found add a new hardware in Homeassistant is not easy for a newbie, and home automation structure also not easily configed in Hass.

So I'm working on a SW that can use blockly to edit home automation though Hass http api. This SW is not released for now.

After I found ioBroker this morning, I found that ioBroker has done a great job that can almost accomplish what I want to do. So I'm very exciting now.
China's smart home industry has gone through a bubble period and is on the road to maturity. There are thousands of hardware companies in China that manufacturing smart home gadgets. More and more Chinese family installed smart home sensors, lights and even toilet seat cover. Homeassistant becomes popular in China, we have done a lot about it.

Almost no one in China has heard that iobroker is a disaster for all Chinese smart home users and enthusiasts. I think this may caused by language disability. So I think we can do a lot for ioBroker, we can write some articles about ioBroker, help enthusiasts install and run ioBroker, we can translate ioBroker homepage into Chinese, we also can run a BBS in China, create a place for ioBroker users in China that can discuss about ioBroker.

Can we do such kind of things in China? Can we got ioBroker's permission and support?

BRs,
Schumy.

### CODE REVIEW

**Comment by SchumyHao** [comment]
Our team is especially willing to promote ioBroker in China. Homeassistant 
ioBroker is much friendly to newbies because most configuration work can be done in frontend, without edit config files directly.
And ioBroker also has great imagination for advanced users because blockly and nodered can be used.

We are willing to complete Chinese translation work for ioBroker adapters, including tutorial documentation.

**Comment by DutchmanNL** [comment]
I think that's incredible great news !!!

We should organise our self for that having translations handled for all could be a very large time related effort and we need to think about a process chain for new adapters if you/your team is willing to handle the language for chinees

**Comment by Apollon77** [comment]
Maybe it could bet he same process as fort he other languages ... basically google translators used  to have basic text coverage and not block the development process. Afterwards checks and maybe localization PRs can optimize the translation when needed ;-)

**Comment by jogibear9988** [comment]
can someone add Chinese to http://www.iobroker.net:3000?
maybe we should look wich languages should also be enabled? Or create a translation on the fly? or create a helper script wich adds missing translations to io-packages.json (by automatically translating english via google translator)

**Comment by jogibear9988** [comment]
sollten wir vlt. auch noch überlegen andere zu unterstützen
https://www.babbel.com/en/magazine/the-10-most-spoken-languages-in-the-world

**Comment by SchumyHao** [comment]
Hi @Apollon77  Thank you for your reply.

I agree with you that use Google translation tools to do basic localization work.

But Chinese is not added as supported language in ioBroker, so I want to done this work

**Comment by SchumyHao** [comment]
> can someone add Chinese to http://www.iobroker.net:3000?
> maybe we should look wich languages should also be enabled? Or create a translation on the fly? or create a helper script wich adds missing translations to io-packages.json (by automatically translating english via google translator)

I'll try to do this work

**Comment by Apollon77** [comment]
Spontan check I would say yes ... but repo is not up to date. :-(( so no ...

Need to check it

**Comment by SchumyHao** [comment]
> Spontan check I would say yes ... but repo is not up to date. :-(( so no ...
> 
> Need to check it

Hi @Apollon77 
I have rebased my branch based on latest commit in ioBroker.admin.

**Comment by ldittmar81** [comment]
@SchumyHao yes, ioBroker.translate is the source code of the translation site. :)

**Comment by Apollon77** [comment]
@ldittmar81 but when you comoare it to the online version it is not the current one but old!! Take care!

**Comment by SchumyHao** [comment]
> @ldittmar81 but when you comoare it to the online version it is not the current one but old!! Take care!

So, how can I got the newest version of ioBroker.translate?

**Comment by SchumyHao** [comment]
I have create a [PR](https://github.com/ioBroker/ioBroker.translate/pull/1) to add Chinese Simplified support in ioBroker.translate. 

I found I need change 'zh' to 'zh-cn' in this PR

**Comment by Apollon77** [comment]
I will try to get it updated today ;-)

**Comment by GermanBluefox** [comment]
Hello,
Sorry, I am a bit busy last time and can answer only with delay :).
I am excited to hear, that iobroker will be used in China by some people.
You will get the full support from me, at least I will try to give the support :). Because, as I said, I am overloaded with 1000 small tasks concerning IoB.
What could be the next steps? If you wish to go in private communication I suggest you contact me via "dogafox at gmail.com".
Regards, 
Bluefox

**Pull request merged**
